# These owners will be the default owners for everything in the repo.
# Unless a later match takes precedence, @julien-rsbrg will be requested for review when someone opens a pull resquest.
* @julien-rsbrg

theme: jekyll-theme-minimal

title: [The title of your site]
description: [A short description of your site's purpose]
